#%RAML 1.0 NamedExample

value:
  userId: 00uajljngIhMt1pzy4x6
  status: ACTIVE
  firstName: Jane
  lastName: Doe
  login: jane.doe@example.com
  email: jane.doe@example.com
  secondEmail: ""
  mobilePhone: "0469112334"
  created: 2020-05-25T16:17:18Z
  activated: 2020-05-25T16:17:18Z
  statusChanged: 2020-05-25T16:17:18Z
  lastLogin: ""
  lastUpdated: 2020-05-25T16:17:18Z
  passwordChanged: 2020-05-25T16:17:18Z