http:
  port: "8084"
  
mytrains-process:
  host: "mytrains-process-api.us-e2.cloudhub.io"
  port: "80"
  basepath: "/api"
  protocol: "HTTP"
  responseTimeout: "10000"
  
notification:
  host: "notifications-process-api.us-e2.cloudhub.io"
  port: "80"
  basepath: "/api"
  protocol: "HTTP"
  responseTimeout: "10000"
  
json:
  logger:
    application:
      name: ${project.artifactId}
      version: ${project.version}
    disabledFields: ""

mule:
  env: ""
      
  