[
  {
    "stationName": "Hall Road",
    "stationCode": "HLR",
	"postalCode": [
          "W1T 5BA",
          "WC1N 1JE",
          "W1W 5JL",
          "WC1N 1HX",
          "EC1M 6EF",
          "W1T 2HF",
          "EC1",
          "EC1M 6BF",
          "W1U 4EX",
          "EC1A 9LH",
          "WC2",
          "W1D 2LR",
          "WC2H 9DP",
          "WC2H 9PR",
          "W1C 2JR",
          "W1F 0PY",
          "W1K 1PX",
          "WC2B 4BB",
          "W1",
          "WC2E 8HB",
          "WC2H 7JE",
          "EC4V 4EG",
          "WC2E 7PG",
          "WC2R 2PH",
          "EC4V 4DY",
          "W1S 4PA",
          "W1J 0DX",
          "W1J 9HW",
          "WC2N 6NG",
          "WC2N 6NS",
          "W1J 8LN",
          "SE1 8XU",
          "SE1 8TG",
          "SE1 8NP",
          "SE1 8LW",
          "SE1 8SW",
          "SE1 7RY",
          "SW1",
          "SW1E 6RD",
          "SW1V 1AN",
          "SW1V 1JU",
          "SW1W 9SJ",
          "SW1W 9RH",
          "SW1W 9TP"
        ]
  },
  {
    "stationName": "University (T & W Metro)",
    "stationCode": "UNV",
	"postalCode": [
          "W1T 5BA",
          "WC1N 1JE",
          "W1W 5JL",
          "WC1N 1HX",
          "EC1M 6EF",
          "W1T 2HF",
          "EC1",
          "EC1M 6BF",
          "W1U 4EX",
          "EC1A 9LH",
          "WC2",
          "W1D 2LR",
          "WC2H 9DP",
          "WC2H 9PR",
          "W1C 2JR",
          "W1F 0PY",
          "W1K 1PX",
          "WC2B 4BB",
          "W1",
          "WC2E 8HB",
          "WC2H 7JE",
          "EC4V 4EG",
          "WC2E 7PG",
          "WC2R 2PH",
          "EC4V 4DY",
          "W1S 4PA",
          "W1J 0DX",
          "W1J 9HW",
          "WC2N 6NG",
          "WC2N 6NS",
          "W1J 8LN",
          "SE1 8XU",
          "SE1 8TG",
          "SE1 8NP",
          "SE1 8LW",
          "SE1 8SW",
          "SE1 7RY",
          "SW1",
          "SW1E 6RD",
          "SW1V 1AN",
          "SW1V 1JU",
          "SW1W 9SJ",
          "SW1W 9RH",
          "SW1W 9TP"
        ]
  },
  {
    "stationName": "Lincoln Central",
    "stationCode": "LCN",
	"postalCode": [
          "W1T 5BA",
          "WC1N 1JE",
          "W1W 5JL",
          "WC1N 1HX",
          "EC1M 6EF",
          "W1T 2HF",
          "EC1",
          "EC1M 6BF",
          "W1U 4EX",
          "EC1A 9LH",
          "WC2",
          "W1D 2LR",
          "WC2H 9DP",
          "WC2H 9PR",
          "W1C 2JR",
          "W1F 0PY",
          "W1K 1PX",
          "WC2B 4BB",
          "W1",
          "WC2E 8HB",
          "WC2H 7JE",
          "EC4V 4EG",
          "WC2E 7PG",
          "WC2R 2PH",
          "EC4V 4DY",
          "W1S 4PA",
          "W1J 0DX",
          "W1J 9HW",
          "WC2N 6NG",
          "WC2N 6NS",
          "W1J 8LN",
          "SE1 8XU",
          "SE1 8TG",
          "SE1 8NP",
          "SE1 8LW",
          "SE1 8SW",
          "SE1 7RY",
          "SW1",
          "SW1E 6RD",
          "SW1V 1AN",
          "SW1V 1JU",
          "SW1W 9SJ",
          "SW1W 9RH",
          "SW1W 9TP"
        ]
  }
  
  ]