db:
  host: "64.227.37.97"
  port: "3306"
  username: "njclabs"
  password: "training"
  database: "nrs"
 
http:
  port: '8081' 
  
json:
  logger:
    application:
      name: "mytrains-system-api"
      version: "1.0.0-SNAPSHOT"
  