http:
  port: "8081"
  request:
    header:
      clientId: "*****"
      clientSecret: "*****"
      
okta:
  host: "*********"
  port: "443"
  
  protocol: "HTTPS"
  
  app:
    token: "SSWS ****************"
    auth:
      url: "/oauth2/default/v1/token?scope=mulescope&grant_type=client_credentials"
      clientId: "*************"
      clientSecret: "*****"

  user:
    basepath: "/api/v1/users?activate=true"
    
    authenticate:
      basepath: "/api/v1/authn"

    forgotPassword:
      basepath: "/credentials/forgot_password?sendEmail=false"
      method: "POST"
      
    changePassword:
      basepath: "/credentials/change_password"
      
    deactivate:
      basepath: "/lifecycle/deactivate"

      
json:
  logger:
    application:
      name: ${project.artifactId}
      version: ${project.version}
    disabledFields: ""

mule:
  env: ""
      